services:
  - type: web
    name: life-planner-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GOOGLE_API_KEY
        sync: false # This will be set manually in the Render dashboard